### ISSUE TITLE
Defining INCF and DECF using DEFINE-MODIFY-MACRO does not play nice with CLTL2

### ISSUE THREAD

**Issue by digikar99** [lisp-polymorph/polymorph.access#7]
```lisp
(in-package :polymorph.maths)
(incf x (the single-float y))
```

The latter macroexpands to

```lisp
(LET* ((#:NUM (THE SINGLE-FLOAT Y)))
  (SETQ X (+ X #:NUM)))
```

With this expansion, the compiler macro of `+` cannot infer the type of `#:NUM`. An appropriate expansion that would let CLTL2 do its work would be:

```lisp
(LET* ((#:NUM (THE SINGLE-FLOAT Y)))
  (DECLARE (TYPE SINGLE-FLOAT #:NUM))
  (SETQ X (+ X #:NUM)))
```

Similarly with `decf`.

**Comment by digikar99** [comment]
A rough sketch of the solution

https://gist.github.com/digikar99/2f1a5b9c89277753558bbdbe12008103

I'm not sure where this code should go in the lisp-polymorph universe.

**Comment by commander-trashdin** [comment]
Working on this, I think I have a shorter solution somewhere.

**Comment by commander-trashdin** [comment]
Done -- please check out polymorph.maths. If all good, close this.

**Comment by digikar99** [comment]
Another case:

```lisp
(incf (aref (the (array single-float) x) 2)
    (the single-float y))
```

Macroexpansion after 0079140f36dfa52851078a3bb9284edc5fa41b86:

```lisp
(LET* ((#:G885 (THE (ARRAY SINGLE-FLOAT) X))
       (#:NEW1
        (+ (THE (ARRAY SINGLE-FLOAT) (AREF #:G885 2)) (THE SINGLE-FLOAT Y))))
  (DECLARE (TYPE (AND (ARRAY SINGLE-FLOAT) (AND SINGLE-FLOAT T)) #:NEW1))
  (FUNCALL #'(SETF AREF) #:NEW1 #:G885 2))
```
This further requires the declaration propagation aka another type declaration form for `#:G885`.

**Comment by commander-trashdin** [comment]
Right, and also this part `(THE (ARRAY SINGLE-FLOAT) (AREF #:G885 2)) ` is clearly wrong. Lemme think about this a bit.

**Comment by digikar99** [comment]
Yup [6eaf8f2](https://github.com/lisp-polymorph/polymorph.maths/commit/6eaf8f23287f5becc8b6be8c471b388a2c41346c) does seem to fix it! Thanks!
